
spring:
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:proxy:h2:mem:///robot_db?proxyListener=io.millesabords.r2dbc.step5.StatementExecListener&DB_CLOSE_DELAY=-1;
    username: sa

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    io.millesabords: DEBUG
